/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:15:29 GMT 2025
 */

package org.apache.flink.connector.rocketmq;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class MetricUtil_ESTest extends MetricUtil_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        MetricUtil metricUtil0 = new MetricUtil();
    }
}
