/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:11:00 GMT 2025
 */

package org.apache.flink.connector.rocketmq.legacy.function;

import org.apache.flink.api.java.tuple.Tuple2;
import org.apache.flink.streaming.api.functions.ProcessFunction;
import org.apache.flink.util.Collector;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class SourceMapFunction_ESTest extends SourceMapFunction_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        SourceMapFunction sourceMapFunction0 = new SourceMapFunction();
        Tuple2<String, String> tuple2_0 =
                (Tuple2<String, String>) mock(Tuple2.class, new ViolatedAssumptionAnswer());
        try {
            sourceMapFunction0.processElement(
                    tuple2_0,
                    (ProcessFunction.Context) null,
                    (Collector<Tuple2<String, String>>) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException(
                    "org.apache.flink.connector.rocketmq.legacy.function.SourceMapFunction", e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        SourceMapFunction sourceMapFunction0 = new SourceMapFunction();
        Tuple2<String, String> tuple2_0 =
                (Tuple2<String, String>) mock(Tuple2.class, new ViolatedAssumptionAnswer());
        ProcessFunction.Context processFunction_Context0 =
                mock(ProcessFunction.Context.class, new ViolatedAssumptionAnswer());
        Collector<Tuple2<String, String>> collector0 =
                (Collector<Tuple2<String, String>>)
                        mock(Collector.class, new ViolatedAssumptionAnswer());
        sourceMapFunction0.processElement(tuple2_0, processFunction_Context0, collector0);
    }
}
