/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:33:01 GMT 2025
 */

package org.apache.flink.connector.rocketmq.common.event;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class SourceDetectEvent_ESTest extends SourceDetectEvent_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        SourceDetectEvent sourceDetectEvent0 = new SourceDetectEvent();
        boolean boolean0 = sourceDetectEvent0.getReSendInitAssign();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        SourceDetectEvent sourceDetectEvent0 = new SourceDetectEvent();
        assertTrue(sourceDetectEvent0.getReSendInitAssign());

        sourceDetectEvent0.setReSendInitAssign(false);
        boolean boolean0 = sourceDetectEvent0.getReSendInitAssign();
        assertFalse(boolean0);
    }
}
