/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:11:43 GMT 2025
 */

package org.apache.flink.connector.rocketmq.source.config;

import org.apache.flink.configuration.description.TextElement;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class OffsetVerification_ESTest extends OffsetVerification_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        OffsetVerification[] offsetVerificationArray0 = OffsetVerification.values();
        assertEquals(2, offsetVerificationArray0.length);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        OffsetVerification offsetVerification0 = OffsetVerification.valueOf("FAIL_ON_MISMATCH");
        assertEquals(OffsetVerification.FAIL_ON_MISMATCH, offsetVerification0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        OffsetVerification offsetVerification0 = OffsetVerification.FAIL_ON_MISMATCH;
        TextElement textElement0 = (TextElement) offsetVerification0.getDescription();
        assertEquals(
                "Fail the consuming from RocketMQ when we don't find the related offset.",
                textElement0.getFormat());
    }
}
