/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:07:48 GMT 2025
 */

package org.apache.flink.connector.rocketmq.source.enumerator.allocate;

import org.apache.flink.connector.rocketmq.source.split.RocketMQSourceSplit;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Collection;
import java.util.Map;
import java.util.Set;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class AverageAllocateStrategy_ESTest extends AverageAllocateStrategy_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        AverageAllocateStrategy averageAllocateStrategy0 = new AverageAllocateStrategy();
        // Undeclared exception!
        try {
            averageAllocateStrategy0.allocate((Collection<RocketMQSourceSplit>) null, 928, 928);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException(
                    "org.apache.flink.connector.rocketmq.source.enumerator.allocate.AverageAllocateStrategy",
                    e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        AverageAllocateStrategy averageAllocateStrategy0 = new AverageAllocateStrategy();
        Map<Integer, Set<RocketMQSourceSplit>> map0 =
                averageAllocateStrategy0.allocate((Collection<RocketMQSourceSplit>) null, (-26));
        assertNull(map0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        AverageAllocateStrategy averageAllocateStrategy0 = new AverageAllocateStrategy();
        String string0 = averageAllocateStrategy0.getStrategyName();
        assertEquals("average", string0);
    }
}
