/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:01:31 GMT 2025
 */

package org.apache.flink.connector.rocketmq.source.enumerator.allocate;

import org.apache.flink.connector.rocketmq.source.split.RocketMQSourceSplit;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Collection;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class ConsistentHashAllocateStrategy_ESTest
        extends ConsistentHashAllocateStrategy_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        ConsistentHashAllocateStrategy consistentHashAllocateStrategy0 =
                new ConsistentHashAllocateStrategy();
        // Undeclared exception!
        try {
            consistentHashAllocateStrategy0.allocate((Collection<RocketMQSourceSplit>) null, 0, 4);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException(
                    "org.apache.flink.connector.rocketmq.source.enumerator.allocate.ConsistentHashAllocateStrategy",
                    e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        ConsistentHashAllocateStrategy consistentHashAllocateStrategy0 =
                new ConsistentHashAllocateStrategy();
        // Undeclared exception!
        try {
            consistentHashAllocateStrategy0.allocate((Collection<RocketMQSourceSplit>) null, 6);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException(
                    "org.apache.flink.connector.rocketmq.source.enumerator.allocate.ConsistentHashAllocateStrategy",
                    e);
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        ConsistentHashAllocateStrategy consistentHashAllocateStrategy0 =
                new ConsistentHashAllocateStrategy();
        String string0 = consistentHashAllocateStrategy0.getStrategyName();
        assertEquals("hash", string0);
    }
}
