/**
 * Scaffolding file used to store all the setups needed to run tests automatically generated by
 * EvoSuite Wed Mar 26 11:13:50 GMT 2025
 */
package org.apache.flink.connector.rocketmq.source.enumerator;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class RocketMQSourceEnumStateSerializer_ESTest_scaffolding {

    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr =
            new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

    private static final java.util.Properties defaultProperties =
            (java.util.Properties) java.lang.System.getProperties().clone();

    private org.evosuite.runtime.thread.ThreadStopper threadStopper =
            new org.evosuite.runtime.thread.ThreadStopper(
                    org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className =
                "org.apache.flink.connector.rocketmq.source.enumerator.RocketMQSourceEnumStateSerializer";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode =
                org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }

    public static void setSystemProperties() {

        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("file.encoding", "UTF-8");
        java.lang.System.setProperty("java.awt.headless", "true");
        java.lang.System.setProperty(
                "java.io.tmpdir", "/var/folders/t3/x2jshcps4n99vnsnf_qb26qm0000gn/T/");
        java.lang.System.setProperty("user.country", "GB");
        java.lang.System.setProperty("user.dir", "/Users/isaac/IdeaProjects/rocketmq-flink");
        java.lang.System.setProperty("user.home", "/Users/isaac");
        java.lang.System.setProperty("user.language", "en");
        java.lang.System.setProperty("user.name", "isaac");
        java.lang.System.setProperty("user.timezone", "America/Toronto");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(
                RocketMQSourceEnumStateSerializer_ESTest_scaffolding.class.getClassLoader(),
                "com.alibaba.fastjson.asm.ClassWriter",
                "com.google.common.primitives.Longs$LongConverter",
                "kotlin.annotation.AnnotationRetention",
                "com.google.common.math.LongMath$1",
                "com.google.common.hash.Striped64$1",
                "com.alibaba.fastjson.util.ASMUtils",
                "com.alibaba.fastjson.JSONPath",
                "com.google.common.hash.Murmur3_128HashFunction$Murmur3_128Hasher",
                "com.alibaba.fastjson.parser.JSONScanner",
                "com.google.common.hash.BloomFilter$Strategy",
                "com.alibaba.fastjson.parser.JSONLexerBase",
                "com.alibaba.fastjson.parser.deserializer.ParseProcess",
                "com.alibaba.fastjson.serializer.JSONSerializable",
                "org.apache.flink.connector.rocketmq.source.enumerator.RocketMQSourceEnumState",
                "com.google.common.collect.NullsLastOrdering",
                "com.alibaba.fastjson.serializer.SerializeWriter",
                "com.alibaba.fastjson.serializer.ReferenceCodec",
                "com.alibaba.fastjson.JSONException",
                "com.alibaba.fastjson.asm.TypeCollector$1",
                "com.google.common.base.Converter$IdentityConverter",
                "com.alibaba.fastjson.parser.ParserConfig$1",
                "com.alibaba.fastjson.parser.ParserConfig$2",
                "com.google.common.collect.ByFunctionOrdering",
                "com.alibaba.fastjson.serializer.SerialContext",
                "com.alibaba.fastjson.serializer.AfterFilter",
                "com.alibaba.fastjson.parser.deserializer.ResolveFieldDeserializer",
                "com.alibaba.fastjson.serializer.MapSerializer",
                "com.alibaba.fastjson.asm.Item",
                "com.alibaba.fastjson.serializer.DateCodec",
                "com.google.common.base.Predicate",
                "com.alibaba.fastjson.parser.deserializer.StackTraceElementDeserializer",
                "com.google.common.hash.Striped64",
                "com.google.common.collect.NullsFirstOrdering",
                "com.google.common.collect.DiscreteDomain$BigIntegerDomain",
                "com.alibaba.fastjson.util.FieldInfo",
                "org.apache.rocketmq.common.message.MessageQueue",
                "com.alibaba.fastjson.serializer.PropertyFilter",
                "com.alibaba.fastjson.serializer.ListSerializer",
                "com.alibaba.fastjson.serializer.NameFilter",
                "com.alibaba.fastjson.util.GenericArrayTypeImpl",
                "com.google.common.base.Strings",
                "com.alibaba.fastjson.serializer.LongCodec",
                "com.alibaba.fastjson.util.Function",
                "com.google.common.collect.DiscreteDomain",
                "com.google.common.collect.UnmodifiableListIterator",
                "kotlin.annotation.AnnotationTarget",
                "com.google.common.collect.Cut",
                "com.alibaba.fastjson.serializer.ContextValueFilter",
                "com.alibaba.fastjson.serializer.ContextObjectSerializer",
                "com.alibaba.fastjson.parser.deserializer.MapDeserializer",
                "com.alibaba.fastjson.serializer.SimplePropertyPreFilter",
                "com.alibaba.fastjson.serializer.AutowiredObjectSerializer",
                "com.google.common.base.ElementTypesAreNonnullByDefault",
                "com.alibaba.fastjson.serializer.StringCodec",
                "com.alibaba.fastjson.serializer.SerializeFilterable",
                "com.google.common.base.Preconditions",
                "com.alibaba.fastjson.JSONStreamAware",
                "com.alibaba.fastjson.asm.MethodWriter",
                "com.alibaba.fastjson.util.TypeUtils$4",
                "com.alibaba.fastjson.util.TypeUtils$5",
                "com.google.common.hash.LongAddables$1",
                "com.alibaba.fastjson.util.TypeUtils$2",
                "com.alibaba.fastjson.util.TypeUtils$3",
                "com.google.common.base.Converter$ConverterComposition",
                "com.alibaba.fastjson.util.TypeUtils$1",
                "com.google.common.collect.ImmutableCollection",
                "com.alibaba.fastjson.util.TypeUtils$8",
                "com.alibaba.fastjson.serializer.CalendarCodec",
                "com.alibaba.fastjson.util.TypeUtils$6",
                "com.alibaba.fastjson.PropertyNamingStrategy$1",
                "com.alibaba.fastjson.util.TypeUtils$7",
                "com.google.common.hash.BloomFilterStrategies",
                "com.alibaba.fastjson.util.TypeUtils",
                "com.alibaba.fastjson.serializer.MiscCodec",
                "com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory",
                "com.alibaba.fastjson.util.IOUtils$1",
                "com.alibaba.fastjson.serializer.IntegerCodec",
                "com.google.errorprone.annotations.DoNotMock",
                "com.google.common.collect.ImmutableCollection$Builder",
                "com.alibaba.fastjson.util.ModuleUtil",
                "com.google.common.hash.AbstractStreamingHasher",
                "com.google.common.collect.DiscreteDomain$IntegerDomain",
                "com.google.common.math.LongMath",
                "com.alibaba.fastjson.parser.deserializer.ExtraProcessable",
                "com.google.common.collect.DiscreteDomain$LongDomain",
                "com.google.common.base.Converter$ReverseConverter",
                "com.google.common.collect.Cut$AboveValue",
                "com.alibaba.fastjson.parser.deserializer.TimeDeserializer",
                "com.alibaba.fastjson.JSONObject",
                "com.alibaba.fastjson.parser.deserializer.SqlDateDeserializer",
                "com.google.common.hash.HashFunction",
                "com.alibaba.fastjson.serializer.CharacterCodec",
                "com.alibaba.fastjson.asm.TypeCollector",
                "com.google.common.hash.LongAdder",
                "com.alibaba.fastjson.util.ASMClassLoader$1",
                "com.alibaba.fastjson.asm.Label",
                "com.alibaba.fastjson.asm.FieldWriter",
                "com.google.common.base.Supplier",
                "com.alibaba.fastjson.util.JavaBeanInfo",
                "com.google.common.hash.LongAddable",
                "com.google.common.hash.Hashing",
                "com.alibaba.fastjson.serializer.SerializeConfig",
                "com.alibaba.fastjson.serializer.AtomicCodec",
                "com.google.common.hash.Striped64$Cell",
                "org.apache.flink.connector.rocketmq.source.enumerator.RocketMQSourceEnumStateSerializer",
                "com.google.common.collect.ImmutableList",
                "com.google.common.collect.ReverseOrdering",
                "com.alibaba.fastjson.serializer.FieldSerializer",
                "com.alibaba.fastjson.parser.JSONReaderScanner",
                "com.alibaba.fastjson.serializer.ValueFilter",
                "com.google.common.hash.LongAddables",
                "com.alibaba.fastjson.JSONPathException",
                "com.alibaba.fastjson.serializer.Labels",
                "com.alibaba.fastjson.parser.deserializer.ThrowableDeserializer",
                "com.google.common.hash.BloomFilter",
                "com.alibaba.fastjson.parser.deserializer.PropertyProcessable",
                "com.google.common.hash.HashCode$BytesHashCode",
                "com.google.common.hash.Java8Compatibility",
                "com.google.common.base.Converter$FunctionBasedConverter",
                "com.alibaba.fastjson.serializer.CharArrayCodec",
                "com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory$Context",
                "com.alibaba.fastjson.asm.MethodVisitor",
                "com.google.common.collect.Ordering",
                "com.alibaba.fastjson.parser.deserializer.NumberDeserializer",
                "com.google.common.collect.NaturalOrdering",
                "com.alibaba.fastjson.serializer.LabelFilter",
                "com.google.common.collect.ElementTypesAreNonnullByDefault",
                "com.alibaba.fastjson.serializer.JavaBeanSerializer",
                "com.alibaba.fastjson.serializer.DoubleSerializer",
                "com.alibaba.fastjson.serializer.ASMSerializerFactory",
                "com.alibaba.fastjson.parser.Feature",
                "com.alibaba.fastjson.parser.ParserConfig",
                "com.alibaba.fastjson.parser.ParseContext",
                "com.google.common.hash.HashCode$LongHashCode",
                "com.google.common.collect.AllEqualOrdering",
                "com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer",
                "com.google.common.collect.ImmutableList$SubList",
                "com.google.common.collect.RegularImmutableList",
                "com.google.common.hash.BloomFilterStrategies$1",
                "kotlin.annotation.Target",
                "com.google.common.hash.BloomFilterStrategies$2",
                "com.alibaba.fastjson.parser.deserializer.FieldTypeResolver",
                "com.alibaba.fastjson.parser.ParserConfig$AutoTypeCheckHandler",
                "org.apache.flink.core.io.Versioned",
                "com.google.common.primitives.Longs",
                "com.alibaba.fastjson.util.BiFunction",
                "com.google.common.collect.Range",
                "com.alibaba.fastjson.serializer.ObjectArrayCodec",
                "com.alibaba.fastjson.serializer.ToStringSerializer",
                "com.alibaba.fastjson.parser.deserializer.PropertyProcessableDeserializer",
                "com.google.common.hash.Funnel",
                "com.alibaba.fastjson.serializer.ObjectSerializer",
                "com.alibaba.fastjson.TypeReference",
                "com.google.common.hash.ElementTypesAreNonnullByDefault",
                "com.alibaba.fastjson.JSONObject$SecureObjectInputStream",
                "org.apache.flink.core.io.SimpleVersionedSerializer",
                "com.google.common.collect.LexicographicalOrdering",
                "com.alibaba.fastjson.parser.deserializer.EnumDeserializer",
                "com.alibaba.fastjson.parser.deserializer.ExtraTypeProvider",
                "com.alibaba.fastjson.parser.DefaultJSONParser$ResolveTask",
                "com.alibaba.fastjson.serializer.BigDecimalCodec",
                "com.google.common.collect.ImmutableAsList",
                "com.alibaba.fastjson.serializer.PrimitiveArraySerializer",
                "com.alibaba.fastjson.annotation.JSONField",
                "com.google.common.collect.RegularImmutableAsList",
                "com.alibaba.fastjson.parser.SymbolTable",
                "com.google.common.collect.Cut$BelowValue",
                "com.alibaba.fastjson.JSONArray",
                "com.alibaba.fastjson.JSONAware",
                "com.alibaba.fastjson.util.ASMClassLoader",
                "com.google.common.collect.UsingToStringOrdering",
                "com.alibaba.fastjson.parser.JSONToken",
                "com.alibaba.fastjson.parser.deserializer.JSONPDeserializer",
                "com.alibaba.fastjson.PropertyNamingStrategy",
                "com.google.common.hash.PrimitiveSink",
                "com.alibaba.fastjson.util.TypeUtils$MethodInheritanceComparator",
                "com.alibaba.fastjson.serializer.AppendableSerializer",
                "com.google.common.hash.Hasher",
                "com.google.common.primitives.IntsMethodsForWeb",
                "com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer",
                "com.google.common.collect.RangeGwtSerializationDependencies",
                "com.alibaba.fastjson.parser.deserializer.AutowiredObjectDeserializer",
                "com.google.common.hash.HashCode",
                "com.alibaba.fastjson.util.ServiceLoader",
                "com.alibaba.fastjson.serializer.ASMSerializerFactory$Context",
                "com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer",
                "com.alibaba.fastjson.parser.DefaultJSONParser",
                "com.google.common.collect.ImmutableList$1",
                "com.alibaba.fastjson.serializer.BeanContext",
                "com.alibaba.fastjson.util.IdentityHashMap",
                "com.alibaba.fastjson.serializer.BigIntegerCodec",
                "com.alibaba.fastjson.JSON",
                "com.google.common.primitives.ElementTypesAreNonnullByDefault",
                "com.alibaba.fastjson.JSONWriter",
                "com.alibaba.fastjson.asm.Opcodes",
                "com.alibaba.fastjson.JSONReader",
                "com.google.common.collect.UnmodifiableIterator",
                "kotlin.Metadata",
                "com.alibaba.fastjson.serializer.SerializeBeanInfo",
                "com.alibaba.fastjson.serializer.SerializerFeature",
                "com.alibaba.fastjson.TypeReference$1",
                "com.alibaba.fastjson.util.IOUtils",
                "com.alibaba.fastjson.parser.deserializer.JavaObjectDeserializer",
                "com.alibaba.fastjson.asm.ClassReader",
                "com.google.errorprone.annotations.Immutable",
                "com.alibaba.fastjson.spi.Module",
                "com.google.common.collect.ImmutableList$ReverseImmutableList",
                "com.google.common.math.ElementTypesAreNonnullByDefault",
                "com.google.common.collect.SingletonImmutableList",
                "com.google.common.base.Converter",
                "kotlin.annotation.MustBeDocumented",
                "com.alibaba.fastjson.serializer.SerializeFilter",
                "com.alibaba.fastjson.JSONPObject",
                "com.google.common.base.Function",
                "com.google.common.collect.ComparatorOrdering",
                "com.google.common.collect.AbstractIndexedListIterator",
                "com.alibaba.fastjson.parser.deserializer.ExtraProcessor",
                "com.google.common.primitives.Ints$IntConverter",
                "com.alibaba.fastjson.serializer.BeforeFilter",
                "com.google.common.hash.AbstractHasher",
                "kotlin.annotation.Retention",
                "com.google.common.collect.BoundType",
                "com.google.common.collect.ExplicitOrdering",
                "com.alibaba.fastjson.util.ParameterizedTypeImpl",
                "com.google.common.collect.ImmutableList$Builder",
                "com.alibaba.fastjson.parser.deserializer.ObjectDeserializer",
                "com.alibaba.fastjson.asm.ByteVector",
                "com.alibaba.fastjson.parser.JSONLexer",
                "com.google.common.collect.Range$1",
                "com.alibaba.fastjson.serializer.JSONSerializer",
                "com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer",
                "com.alibaba.fastjson.parser.deserializer.ContextObjectDeserializer",
                "com.google.common.collect.CompoundOrdering",
                "com.alibaba.fastjson.serializer.FieldSerializer$RuntimeSerializerInfo",
                "com.alibaba.fastjson.asm.Type",
                "com.google.common.hash.AbstractHashFunction",
                "com.google.common.hash.Murmur3_128HashFunction",
                "com.google.common.collect.Ordering$IncomparableValueException",
                "com.alibaba.fastjson.serializer.FloatCodec",
                "com.google.common.hash.BloomFilterStrategies$LockFreeBitArray",
                "com.alibaba.fastjson.parser.deserializer.FieldDeserializer",
                "com.google.common.collect.Cut$BelowAll",
                "com.alibaba.fastjson.serializer.CollectionCodec",
                "com.google.common.collect.ReverseNaturalOrdering",
                "com.google.common.primitives.Ints",
                "com.google.common.hash.HashCode$IntHashCode",
                "com.alibaba.fastjson.asm.MethodCollector",
                "com.alibaba.fastjson.annotation.JSONType",
                "com.alibaba.fastjson.util.IdentityHashMap$Entry",
                "com.google.common.collect.Cut$AboveAll",
                "com.alibaba.fastjson.serializer.BooleanCodec",
                "com.alibaba.fastjson.serializer.PropertyPreFilter");
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance()
                .setClassLoader(
                        RocketMQSourceEnumStateSerializer_ESTest_scaffolding.class
                                .getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
                "org.apache.flink.connector.rocketmq.source.enumerator.RocketMQSourceEnumStateSerializer",
                "com.alibaba.fastjson.parser.Feature",
                "com.alibaba.fastjson.serializer.SerializerFeature",
                "com.alibaba.fastjson.util.IOUtils$1",
                "com.alibaba.fastjson.util.IOUtils",
                "com.alibaba.fastjson.JSON",
                "com.alibaba.fastjson.util.IdentityHashMap",
                "com.alibaba.fastjson.util.ASMUtils",
                "com.alibaba.fastjson.parser.SymbolTable",
                "com.alibaba.fastjson.util.TypeUtils$1",
                "com.alibaba.fastjson.util.TypeUtils$2",
                "com.alibaba.fastjson.util.TypeUtils$3",
                "com.alibaba.fastjson.util.TypeUtils$4",
                "com.alibaba.fastjson.util.TypeUtils$5",
                "com.alibaba.fastjson.util.TypeUtils$6",
                "com.alibaba.fastjson.util.ModuleUtil",
                "com.alibaba.fastjson.util.TypeUtils$7",
                "com.alibaba.fastjson.util.TypeUtils$8",
                "com.alibaba.fastjson.util.TypeUtils",
                "com.alibaba.fastjson.parser.ParserConfig$1",
                "com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory",
                "com.alibaba.fastjson.util.ASMClassLoader$1",
                "com.alibaba.fastjson.util.ASMClassLoader",
                "com.alibaba.fastjson.serializer.MiscCodec",
                "com.alibaba.fastjson.util.IdentityHashMap$Entry",
                "com.alibaba.fastjson.parser.deserializer.ContextObjectDeserializer",
                "com.alibaba.fastjson.serializer.CalendarCodec",
                "com.alibaba.fastjson.parser.deserializer.MapDeserializer",
                "com.alibaba.fastjson.serializer.CollectionCodec",
                "com.alibaba.fastjson.parser.deserializer.JavaObjectDeserializer",
                "com.alibaba.fastjson.serializer.StringCodec",
                "com.alibaba.fastjson.serializer.CharacterCodec",
                "com.alibaba.fastjson.parser.deserializer.NumberDeserializer",
                "com.alibaba.fastjson.serializer.IntegerCodec",
                "com.alibaba.fastjson.serializer.LongCodec",
                "com.alibaba.fastjson.serializer.BigIntegerCodec",
                "com.alibaba.fastjson.serializer.BigDecimalCodec",
                "com.alibaba.fastjson.serializer.FloatCodec",
                "com.alibaba.fastjson.serializer.BooleanCodec",
                "com.alibaba.fastjson.serializer.CharArrayCodec",
                "com.alibaba.fastjson.serializer.ReferenceCodec",
                "com.alibaba.fastjson.serializer.AtomicCodec",
                "com.alibaba.fastjson.parser.deserializer.StackTraceElementDeserializer",
                "com.alibaba.fastjson.parser.deserializer.JSONPDeserializer",
                "com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer",
                "com.alibaba.fastjson.parser.deserializer.SqlDateDeserializer",
                "com.alibaba.fastjson.parser.deserializer.TimeDeserializer",
                "com.alibaba.fastjson.serializer.DateCodec",
                "com.alibaba.fastjson.parser.ParserConfig$2",
                "com.alibaba.fastjson.parser.ParserConfig",
                "com.alibaba.fastjson.serializer.ASMSerializerFactory",
                "com.alibaba.fastjson.serializer.DoubleSerializer",
                "com.alibaba.fastjson.serializer.PrimitiveArraySerializer",
                "com.alibaba.fastjson.serializer.ObjectArrayCodec",
                "com.alibaba.fastjson.serializer.AppendableSerializer",
                "com.alibaba.fastjson.serializer.ToStringSerializer",
                "com.alibaba.fastjson.serializer.SerializeConfig",
                "org.apache.flink.connector.rocketmq.source.enumerator.RocketMQSourceEnumState",
                "com.alibaba.fastjson.serializer.SerializeWriter",
                "com.alibaba.fastjson.serializer.SerializeFilterable",
                "com.alibaba.fastjson.serializer.JSONSerializer",
                "com.alibaba.fastjson.util.ServiceLoader",
                "com.alibaba.fastjson.util.TypeUtils$MethodInheritanceComparator",
                "com.alibaba.fastjson.util.FieldInfo",
                "com.alibaba.fastjson.serializer.SerializeBeanInfo",
                "com.alibaba.fastjson.serializer.JavaBeanSerializer",
                "com.alibaba.fastjson.serializer.FieldSerializer",
                "com.alibaba.fastjson.serializer.BeanContext",
                "com.alibaba.fastjson.serializer.SerialContext",
                "com.alibaba.fastjson.serializer.FieldSerializer$RuntimeSerializerInfo",
                "com.alibaba.fastjson.serializer.ListSerializer",
                "com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer",
                "com.alibaba.fastjson.parser.deserializer.ThrowableDeserializer",
                "com.alibaba.fastjson.util.JavaBeanInfo",
                "com.alibaba.fastjson.asm.ClassReader",
                "com.alibaba.fastjson.asm.TypeCollector$1",
                "com.alibaba.fastjson.asm.TypeCollector",
                "com.alibaba.fastjson.asm.Type",
                "com.alibaba.fastjson.asm.MethodCollector",
                "com.alibaba.fastjson.JSONException",
                "com.alibaba.fastjson.parser.JSONLexerBase",
                "com.alibaba.fastjson.parser.JSONScanner",
                "com.alibaba.fastjson.parser.DefaultJSONParser",
                "com.alibaba.fastjson.asm.ClassWriter",
                "com.alibaba.fastjson.asm.ByteVector",
                "com.alibaba.fastjson.asm.Item",
                "com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory$Context",
                "com.alibaba.fastjson.asm.MethodWriter",
                "com.alibaba.fastjson.asm.Label",
                "com.alibaba.fastjson.util.GenericArrayTypeImpl",
                "org.apache.rocketmq.common.message.MessageQueue",
                "com.alibaba.fastjson.serializer.ASMSerializerFactory$Context",
                "com.alibaba.fastjson.asm.FieldWriter",
                "com.alibaba.fastjson.parser.deserializer.FieldDeserializer",
                "com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer",
                "com.alibaba.fastjson.parser.JSONReaderScanner",
                "com.alibaba.fastjson.util.ParameterizedTypeImpl",
                "com.alibaba.fastjson.parser.JSONToken",
                "com.google.common.hash.BloomFilter",
                "com.google.common.hash.BloomFilterStrategies",
                "com.google.common.base.Preconditions",
                "com.google.common.base.Strings",
                "com.google.common.hash.BloomFilterStrategies$LockFreeBitArray",
                "com.google.common.math.LongMath",
                "com.google.common.math.LongMath$1",
                "com.google.common.primitives.IntsMethodsForWeb",
                "com.google.common.primitives.Ints",
                "com.google.common.hash.Striped64$1",
                "com.google.common.hash.Striped64",
                "com.google.common.hash.LongAdder",
                "com.google.common.hash.LongAddables$1",
                "com.google.common.hash.LongAddables",
                "com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer",
                "com.alibaba.fastjson.PropertyNamingStrategy$1",
                "com.alibaba.fastjson.parser.deserializer.PropertyProcessableDeserializer",
                "com.alibaba.fastjson.serializer.SimplePropertyPreFilter",
                "com.google.common.hash.Hashing",
                "com.google.common.hash.AbstractHashFunction",
                "com.google.common.hash.Murmur3_128HashFunction",
                "com.google.common.hash.AbstractHasher",
                "com.google.common.hash.AbstractStreamingHasher",
                "com.google.common.hash.Murmur3_128HashFunction$Murmur3_128Hasher",
                "com.google.common.hash.Java8Compatibility",
                "com.google.common.hash.HashCode",
                "com.google.common.hash.HashCode$BytesHashCode",
                "com.google.common.primitives.Longs",
                "com.alibaba.fastjson.parser.deserializer.EnumDeserializer",
                "com.google.common.collect.RangeGwtSerializationDependencies",
                "com.google.common.collect.Cut",
                "com.google.common.collect.Cut$BelowAll",
                "com.google.common.collect.Cut$AboveAll",
                "com.google.common.collect.Range",
                "com.google.common.collect.Range$1",
                "com.google.common.collect.Cut$BelowValue");
    }
}
