/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:35:53 GMT 2025
 */

package org.apache.flink.connector.rocketmq.source.metrics;

import org.apache.flink.metrics.groups.SourceReaderMetricGroup;

import org.apache.rocketmq.common.message.MessageQueue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class RocketMQSourceReaderMetrics_ESTest
        extends RocketMQSourceReaderMetrics_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        SourceReaderMetricGroup sourceReaderMetricGroup0 =
                mock(SourceReaderMetricGroup.class, new ViolatedAssumptionAnswer());
        RocketMQSourceReaderMetrics rocketMQSourceReaderMetrics0 =
                new RocketMQSourceReaderMetrics(sourceReaderMetricGroup0);
        MessageQueue messageQueue0 = mock(MessageQueue.class, new ViolatedAssumptionAnswer());
        rocketMQSourceReaderMetrics0.registerNewMessageQueue(messageQueue0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        SourceReaderMetricGroup sourceReaderMetricGroup0 =
                mock(SourceReaderMetricGroup.class, new ViolatedAssumptionAnswer());
        RocketMQSourceReaderMetrics rocketMQSourceReaderMetrics0 =
                new RocketMQSourceReaderMetrics(sourceReaderMetricGroup0);
        MessageQueue messageQueue0 = mock(MessageQueue.class, new ViolatedAssumptionAnswer());
        rocketMQSourceReaderMetrics0.unregisterMessageQueue(messageQueue0);
    }
}
