/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:09:55 GMT 2025
 */

package org.apache.flink.connector.rocketmq.legacy.common.selector;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class DefaultTopicSelector_ESTest extends DefaultTopicSelector_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        DefaultTopicSelector<Integer> defaultTopicSelector0 =
                new DefaultTopicSelector<Integer>((String) null);
        Integer integer0 = new Integer(0);
        String string0 = defaultTopicSelector0.getTopic(integer0);
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        DefaultTopicSelector<String> defaultTopicSelector0 =
                new DefaultTopicSelector<String>("", (String) null);
        String string0 = defaultTopicSelector0.getTag("");
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        DefaultTopicSelector<String> defaultTopicSelector0 =
                new DefaultTopicSelector<String>("", ")oD-FVVA,({p>J)&\"qq");
        String string0 = defaultTopicSelector0.getTag("hp6A}mfD");
        assertEquals(")oD-FVVA,({p>J)&\"qq", string0);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        DefaultTopicSelector<Object> defaultTopicSelector0 =
                new DefaultTopicSelector<Object>("S9-awb#@jsnEH83", "");
        String string0 = defaultTopicSelector0.getTopic("");
        assertEquals("S9-awb#@jsnEH83", string0);
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        DefaultTopicSelector<Integer> defaultTopicSelector0 = new DefaultTopicSelector<Integer>("");
        Integer integer0 = new Integer(941);
        String string0 = defaultTopicSelector0.getTopic(integer0);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        DefaultTopicSelector<Integer> defaultTopicSelector0 = new DefaultTopicSelector<Integer>("");
        Integer integer0 = new Integer(941);
        String string0 = defaultTopicSelector0.getTag(integer0);
        assertEquals("", string0);
    }
}
