/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:29:45 GMT 2025
 */

package org.apache.flink.connector.rocketmq.sink.writer.serializer;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class RocketMQSerializationSchema_ESTest
        extends RocketMQSerializationSchema_ESTest_scaffolding {
    @Test
    public void notGeneratedAnyTest() {
        // EvoSuite did not generate any tests
    }
}
