/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:12:46 GMT 2025
 */

package org.apache.flink.connector.rocketmq.sink.writer.serializer;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class RocketMQSerializerWrapper_ESTest extends RocketMQSerializerWrapper_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        RocketMQSerializerWrapper rocketMQSerializerWrapper0 = new RocketMQSerializerWrapper();
    }
}
