/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 11:55:00 GMT 2025
 */

package org.apache.flink.connector.rocketmq.sink.table;

import org.apache.flink.configuration.ConfigOption;
import org.apache.flink.table.catalog.ResolvedCatalogTable;
import org.apache.flink.table.factories.DynamicTableFactory;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Map;
import java.util.Set;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class RocketMQDynamicTableSinkFactory_ESTest
        extends RocketMQDynamicTableSinkFactory_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        RocketMQDynamicTableSinkFactory rocketMQDynamicTableSinkFactory0 =
                new RocketMQDynamicTableSinkFactory();
        ResolvedCatalogTable resolvedCatalogTable0 =
                mock(ResolvedCatalogTable.class, new ViolatedAssumptionAnswer());
        doReturn((Map) null).when(resolvedCatalogTable0).getOptions();
        DynamicTableFactory.Context dynamicTableFactory_Context0 =
                mock(DynamicTableFactory.Context.class, new ViolatedAssumptionAnswer());
        doReturn(resolvedCatalogTable0).when(dynamicTableFactory_Context0).getCatalogTable();
        // Undeclared exception!
        try {
            rocketMQDynamicTableSinkFactory0.createDynamicTableSink(dynamicTableFactory_Context0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.flink.configuration.Configuration", e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        RocketMQDynamicTableSinkFactory rocketMQDynamicTableSinkFactory0 =
                new RocketMQDynamicTableSinkFactory();
        Set<ConfigOption<?>> set0 = rocketMQDynamicTableSinkFactory0.requiredOptions();
        assertFalse(set0.isEmpty());
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        RocketMQDynamicTableSinkFactory rocketMQDynamicTableSinkFactory0 =
                new RocketMQDynamicTableSinkFactory();
        Set<ConfigOption<?>> set0 = rocketMQDynamicTableSinkFactory0.optionalOptions();
        assertFalse(set0.isEmpty());
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        RocketMQDynamicTableSinkFactory rocketMQDynamicTableSinkFactory0 =
                new RocketMQDynamicTableSinkFactory();
        String string0 = rocketMQDynamicTableSinkFactory0.factoryIdentifier();
        assertEquals("rocketmq", string0);
    }
}
