/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:19:33 GMT 2025
 */

package org.apache.flink.connector.rocketmq.common.config;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class RocketMQOptions_ESTest extends RocketMQOptions_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        RocketMQOptions rocketMQOptions0 = new RocketMQOptions();
    }
}
