/**
 * Scaffolding file used to store all the setups needed to run tests automatically generated by
 * EvoSuite Wed Mar 26 12:17:21 GMT 2025
 */
package org.apache.flink.connector.rocketmq.legacy.common.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

import static org.evosuite.shaded.org.mockito.Mockito.*;

@EvoSuiteClassExclude
public class MetricUtils_ESTest_scaffolding {

    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr =
            new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

    private static final java.util.Properties defaultProperties =
            (java.util.Properties) java.lang.System.getProperties().clone();

    private org.evosuite.runtime.thread.ThreadStopper threadStopper =
            new org.evosuite.runtime.thread.ThreadStopper(
                    org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className =
                "org.apache.flink.connector.rocketmq.legacy.common.util.MetricUtils";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode =
                org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        try {
            initMocksToAvoidTimeoutsInTheTests();
        } catch (ClassNotFoundException e) {
        }
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }

    public static void setSystemProperties() {

        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("file.encoding", "UTF-8");
        java.lang.System.setProperty("java.awt.headless", "true");
        java.lang.System.setProperty(
                "java.io.tmpdir", "/var/folders/t3/x2jshcps4n99vnsnf_qb26qm0000gn/T/");
        java.lang.System.setProperty("user.country", "GB");
        java.lang.System.setProperty("user.dir", "/Users/isaac/IdeaProjects/rocketmq-flink");
        java.lang.System.setProperty("user.home", "/Users/isaac");
        java.lang.System.setProperty("user.language", "en");
        java.lang.System.setProperty("user.name", "isaac");
        java.lang.System.setProperty("user.timezone", "America/Toronto");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(
                MetricUtils_ESTest_scaffolding.class.getClassLoader(),
                "org.apache.flink.api.common.functions.RuntimeContext",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$LatestCompletedCheckpointPersistedDataGauge",
                "org.apache.flink.api.common.state.ReducingStateDescriptor",
                "org.apache.flink.metrics.CharacterFilter",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$LatestCompletedCheckpointProcessedDataGauge",
                "org.apache.flink.runtime.metrics.TimerGauge",
                "org.apache.flink.api.common.state.ListState",
                "org.apache.flink.api.common.state.AggregatingState",
                "org.apache.flink.api.common.state.ReducingState",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$InProgressCheckpointsCounter",
                "org.apache.flink.api.common.state.ListStateDescriptor",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$LatestCompletedCheckpointSizeGauge",
                "org.apache.flink.api.common.state.State",
                "org.apache.flink.connector.rocketmq.legacy.common.util.MetricUtils$LatencyGauge",
                "org.apache.flink.metrics.MeterView",
                "org.apache.flink.connector.rocketmq.legacy.common.util.MetricUtils$TimestampGauge",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$LatestRestoredCheckpointTimestampGauge",
                "org.apache.flink.util.AbstractID",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$LatestCompletedCheckpointExternalPathGauge",
                "org.apache.flink.connector.rocketmq.legacy.common.util.MetricUtils",
                "org.apache.flink.api.common.accumulators.Accumulator",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$LatestCompletedCheckpointDurationGauge",
                "org.apache.flink.api.common.cache.DistributedCache",
                "org.apache.flink.api.common.externalresource.ExternalResourceInfo",
                "org.apache.flink.api.common.functions.IterationRuntimeContext",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$LatestCompletedCheckpointFullSizeGauge",
                "org.apache.flink.metrics.Meter",
                "org.apache.flink.metrics.MetricGroup",
                "org.apache.flink.api.common.state.ValueState",
                "org.apache.flink.api.common.ExecutionConfig",
                "org.apache.flink.api.common.functions.BroadcastVariableInitializer",
                "org.apache.flink.api.common.accumulators.Histogram",
                "org.apache.flink.metrics.Counter",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$FailedCheckpointsCounter",
                "org.apache.flink.api.common.accumulators.DoubleCounter",
                "org.apache.flink.api.common.state.AppendingState",
                "org.apache.flink.api.common.accumulators.LongCounter",
                "org.apache.flink.api.common.state.MapStateDescriptor",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$CompletedCheckpointsCounter",
                "org.apache.flink.metrics.Metric",
                "org.apache.flink.metrics.Histogram",
                "org.apache.flink.api.common.functions.util.RuntimeUDFContext",
                "org.apache.flink.metrics.groups.UnregisteredMetricsGroup$DummyGauge",
                "org.apache.flink.metrics.groups.OperatorMetricGroup",
                "org.apache.flink.metrics.groups.OperatorIOMetricGroup",
                "org.apache.flink.metrics.Gauge",
                "org.apache.flink.api.common.accumulators.IntCounter",
                "org.apache.flink.metrics.SimpleCounter",
                "org.apache.flink.api.common.state.AggregatingStateDescriptor",
                "org.apache.flink.api.common.Archiveable",
                "org.apache.flink.api.common.state.StateDescriptor",
                "org.apache.flink.api.common.functions.util.AbstractRuntimeUDFContext",
                "org.apache.flink.api.common.accumulators.SimpleAccumulator",
                "org.apache.flink.metrics.View",
                "org.apache.flink.api.common.state.MergingState",
                "org.apache.flink.api.common.state.ValueStateDescriptor",
                "org.apache.flink.runtime.checkpoint.CheckpointStatsTracker$CheckpointsCounter",
                "org.apache.flink.api.common.JobID",
                "org.apache.flink.api.common.state.MapState");
    }

    private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException {
        mock(
                Class.forName(
                        "org.apache.flink.api.common.functions.RuntimeContext",
                        false,
                        MetricUtils_ESTest_scaffolding.class.getClassLoader()));
        mock(
                Class.forName(
                        "org.apache.flink.metrics.Gauge",
                        false,
                        MetricUtils_ESTest_scaffolding.class.getClassLoader()));
        mock(
                Class.forName(
                        "org.apache.flink.metrics.MetricGroup",
                        false,
                        MetricUtils_ESTest_scaffolding.class.getClassLoader()));
        mock(
                Class.forName(
                        "org.apache.flink.metrics.groups.OperatorMetricGroup",
                        false,
                        MetricUtils_ESTest_scaffolding.class.getClassLoader()));
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance()
                .setClassLoader(MetricUtils_ESTest_scaffolding.class.getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
                "org.apache.flink.connector.rocketmq.legacy.common.util.MetricUtils",
                "org.apache.flink.connector.rocketmq.legacy.common.util.MetricUtils$LatencyGauge",
                "org.apache.flink.connector.rocketmq.legacy.common.util.MetricUtils$TimestampGauge",
                "org.apache.flink.metrics.SimpleCounter",
                "org.apache.flink.metrics.MeterView");
    }
}
