/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 12:28:16 GMT 2025
 */

package org.apache.flink.connector.rocketmq.legacy.common.util;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
        mockJVMNonDeterminism = true,
        useVFS = true,
        useVNET = true,
        resetStaticState = true,
        separateClassLoader = true,
        useJEE = true)
public class TestUtils_ESTest extends TestUtils_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        // Undeclared exception!
        try {
            TestUtils.getFieldValue(
                    "org.apache.flink.connector.rocketmq.legacy.common.util.TestUtils",
                    (String) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        try {
            TestUtils.getFieldValue("7ky>/HLTL#X])3}", "");
            fail("Expecting exception: NoSuchFieldException");

        } catch (NoSuchFieldException e) {
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        TestUtils.setFieldValue("7ky>/HLTL#X])3}", "7ky>/HLTL#X])3}", "7ky>/HLTL#X])3}");
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        TestUtils testUtils0 = new TestUtils();
        TestUtils.setFieldValue("l", "l", testUtils0);
    }
}
